---
title: "Research"
output:
  html_document:
    theme: flatly
urlcolor: blue
linkcolor: blue	
citecolor: blue

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
  
<br />
  
### **Job Market Paper** <a class="btn btn-primary" href="https://andrewproctor.github.io/assets/JMP_AndrewProctor.pdf" role="button">PDF</a> 
  
*Did the apple fall far from the tree?
  Uncertainty and learning about ability with family-informed priors* 

**Abstract:**
This paper examines the effect of uncertainty and learning about ability on 
intergenerational correlations in education and labor market outcomes, when children and
their parents utilize family signals to inform initial beliefs about ability. I examine
this question by using a cohort study and rich administrative data to estimate
a dynamic discrete choice structural model of education and occupational decisions,
incorporating multidimensional skills and ability endowments, as well as uncertainty
and learning about ability, starting from a family-driven prior.

<br />

#### **Publications**

##### *Crowdsourcing hypothesis tests: Making transparent how design choices shape research results* (joint with Landy et. al.)
###### (joint with Landy et. al.)


<a class="btn btn-primary" href="https://psycnet.apa.org/doiLanding?doi=10.1037%2Fbul0000220" role="button">Publication</a> 
<a class="btn btn-primary" href="https://andrewproctor.github.io/assets/Landy-et-al.-2020-PsychologicalBulletin.pdf" role="button">Ungated PDF</a> 

**Abstract:**
To what extent are research results influenced by subjective decisions that scientists make as they design studies? Fifteen research teams independently designed studies to answer five original research questions related to moral judgments, negotiations, and implicit cognition. Participants from 2 separate large samples (total N > 15,000) were then randomly assigned to complete 1 version of each study. Effect sizes varied dramatically across different sets of materials designed to test the same hypothesis: Materials from different teams rendered statistically significant effects in opposite directions for 4 of 5 hypotheses, with the narrowest range in estimates being d = -0.37 to + 0.26. Meta-analysis and a Bayesian perspective on the results revealed overall support for 2 hypotheses and a lack of support for 3 hypotheses. Overall, practically none of the variability in effect sizes was attributable to the skill of the research team in designing materials, whereas considerable variability was attributable to the hypothesis being tested. In a forecasting survey, predictions of other scientists were significantly correlated with study results, both across and within hypotheses. Crowdsourced testing of research hypotheses helps reveal the true consistency of empirical support for a scientific claim.

<br />

#### **Works in Progress** <br />

##### *Gender differences in perceived abilities and career sorting* 
###### (joint with Shubhaa Bhattacharyya and Patrizia Massner)


**Abstract:**
Despite the increase in female labor force participation over the last decades,
occupations and college majors continue to exhibit high levels of segregation
between genders. Do gendered biases in beliefs about abilities affect this career
sorting? In this study, we investigate the role of gender differences
in self-perceived abilities on human capital investment paths, such as choice of
subject in upper secondary schooling and the choice of college major. Using
nationally representative panel survey data from the Evaluation Through Follow-Up
(ETF) Study in Sweden, we document the presence of large gender-biases in 
self-perceptions of subject-specific ability by gender.  We explore the magnitude and 
consequences of gender-biased beliefs for career sorting by structurally estimating a 
dynamic model of human capital investments that incorporates limited information about ability, 
with ability beliefs that may deviate from rational expectations through biased beliefs. 
By estimating the structural model using longitudinal ETF survey data matched to Swedish 
administrative data, we examine the extent to which gender-specific biases in self-perceived 
abilities can explain educational and occupational sorting in the Swedish labor market.

<br />

##### *Bundling Frictions of Tiebout Choice in the sub-Metropolis * 

**Abstract:**
Tiebout choice assumes that there exists a sufficient number of communities in a housing market to allow each household to choose a residence that matches their preferences for residential characteristics, which in the simplest versions of the Tiebout model consists of only preferences for public goods. In practice, the residential choice decision bundles a number of residential characteristics over which households have preferences, including public goods like schooling, but also the quality and type of housing, the composition of one's neighbors (and students' peers), the distance from work, and many other attributes still. This diverse array of considerations implies that the requisite number of communities in order for a household to obtain its desired bundle may be very large --- a condition perhaps approximated only in large urban metropolises. This paper considers the extent to which departures from this assumption affect allocative efficiency and welfare in smaller housing markets. This question is analyzed by first estimating an equilibrium sorting model of the housing market for several markets of varying sizes. Counterfactual analysis then characterizes the welfare costs of bundling schooling quality with non-schooling amenities, both across market sizes and by household type within a given market size. 

<br />

##### *A Modified Klein-Spady Estimator for Binary Choice Models* 
  
**Abstract:**
One of the most cited studies within the field of binary choice models is that of Klein 
and Spady (1993), in which a semiparametric estimator is proposed that makes
no assumption concerning the functional form of the choice probability function.
However, although theoretically appealing, the estimator has been found to be 
difficult to implement. This paper proposes a modified version of the Klein-Spady
estimator, which is shown to be relatively easy to implement, is numerically more
stable and performs better in simulations relative to the Klein-Spady estimator.

<br />

##### *Careers of the Extremely Intelligent* 
###### (joint with Erik Lindqvist and Jonas Vlachos)

**Abstract:**
A vast literature documents the pivotal role played by skills in the modern economy.  However, little is known about the return to extreme levels of cognitive skill, and whether being a ''genius'' is rewarded in the labor market. In this paper,
we use data on a quarter century of Swedish draftees (about one million men) to investigate the relationship between labor market outcomes and cognitive skill at the high end of the cognitive skill distribution (up to +3.5 SDs). Our preliminary results suggest the relationship between wages and cognitive skill follows an S-shaped pattern, with returns  to cognitive skill eventually turning negative above +2.5 SDs. We find the comparatively low non-cognitive skill of highly intelligent men explain part of their relatively low wages, and are currently investigating the role of educational and occupational
choices.

<br />

##### *Socio-economic background and beliefs about the consumption value of education* 
###### (joint with Arnaud Maurel)

**Abstract:**
Recent work has emphasized that education and career decisions are decided not only on the basis of
expected financial returns, but also critically  depend on the expected non-pecuniary enjoyment derived 
from these choices. Yet nearly all such analyses have treated the non-pecuniary consumption value of choices
as known ex-ante by the agent, when in practice many of these components are not directly observable. Both the content and precision of these beliefs thus may depend on whether the agent has role models or peers
that have experience with a prospective choice, and if so, what these experiences were like. This study examines how  beliefs about non-pecuniary aspects of future educational decisions vary by socio-economic background, how these beliefs evolve, and how closely these beliefs correspond to subsequent experiences. This analysis is performed using detailed longitudinal data on students' educational experiences and elicited beliefs about future educational experiences for a large sample of Swedish youth. Structural analysis will then consider how heterogeneous and potentially misspecified  beliefs about the non-pecuniary enjoyment of education affects the educational investment and sorting decisions of youth differentially by socio-economic background.