---
title: "Teaching"
output:
  html_document:
    theme: flatly
urlcolor: blue
linkcolor: blue	
citecolor: blue

---

<br>


### **Empirical Economics (SSE Bachelors Course 651) - 2017**

<br>
<div class = "col-xs-11 col-md-12">

#### **Slides**

  <a href="https://andrewproctor.github.io/assets/StataSeminar1and2.pdf" 
  style="color:teal;">Introduction to Stata (Seminar I and II)</a>
  
  <a href="https://andrewproctor.github.io/assets/StataSeminar3.pdf" 
  style="color:teal;">Violations of Regression Assumptions and Methods for Longitudinal Data (Stata Seminar III)</a><br>
  
  <a href="https://andrewproctor.github.io/assets/StataSeminar4.pdf" 
  style="color:teal;">Instrumental Variables Regression (Stata Seminar IV)</a><br><br /><br />
  
  
</div>
<div class = "row">
<div class = "col-md-6">
<div class = "col-xs-1 col-md-0"></div>
<div class = "col-xs-11 col-md-12">
#### **Assignments**

**Assignment 1**: <a href="https://andrewproctor.github.io/assets/Assignment-1.pdf" style="color:teal;">Instructions</a> | 
  <a href="https://andrewproctor.github.io/assets/Assignment-1-Theory-Solutions.pdf" style="color:teal;">Theory Solutions</a> | 
  <a href="https://andrewproctor.github.io/assets/Assignment-1-do-file.pdf" style="color:teal;">Do File</a> | 
  <a href="https://andrewproctor.github.io/assets/Assignment-1-log-file.txt" style="color:teal;">Log File</a>

**Assignment 2**: <a href="https://andrewproctor.github.io/assets/Assignment-2.pdf" style="color:teal;">Instructions</a> | 
  <a href="https://andrewproctor.github.io/assets/Assignment-2-Theory-Solutions.pdf" style="color:teal;">Theory Solutions</a> | 
  <a href="https://andrewproctor.github.io/assets/Assignment-2-do-file.pdf" style="color:teal;">Do File</a>  | 
  <a href="https://andrewproctor.github.io/assets/Assignment-2-log-file.txt" style="color:teal;">Log File</a>

**Assignment 3**: <a href="https://andrewproctor.github.io/assets/Assignment-3.pdf" style="color:teal;">Instructions</a> | 
  <a href="https://andrewproctor.github.io/assets/Assignment-3-Theory-Solutions.pdf" style="color:teal;">Theory Solutions</a> | 
  <a href="https://andrewproctor.github.io/assets/Assignment-3-do-file.pdf" style="color:teal;">Do File</a> | 
  <a href="https://andrewproctor.github.io/assets/Assignment-3-log-file.txt" style="color:teal;">Log File</a>

<br>

</div></div>
<div class = "col-md-6">
<div class = "col-xs-1 col-md-0"></div>
<div class = "col-xs-11 col-md-12">

#### **Case-Based Seminars**

**Seminar 1**: <a href="https://andrewproctor.github.io/assets/Case-Based-Seminar-1-Instructions.pdf" style="color:teal;">Instructions</a> | 
  <a href="https://andrewproctor.github.io/assets/Case-Based-Seminar-1-Slides.pdf" style="color:teal;">Slides</a>
  
**Seminar 2**: <a href="https://andrewproctor.github.io/assets/Case-Based-Seminar-2-Instructions.pdf" style="color:teal;">Instructions</a> | 
  <a href="https://andrewproctor.github.io/assets/Case-Based-Seminar-2-Slides.pdf" style="color:teal;">Slides</a>
  
<br>
<br>

</div></div>

### **Empirical Economics - 2018 (Second Half)**

<br>

<div class = "col-xs-11 col-md-12">

#### **Slides**

  <a href="https://andrewproctor.github.io/assets/panelseminar_slides_2018.pdf" style="color:teal;">Panel Data Regression</a>
  
  <a href="https://andrewproctor.github.io/assets/IVseminar_slides_2018.pdf" style="color:teal;">Instrumental Variables Regression</a>
  
  **IV Seminar Supplement --- **   Correcting standard errors when doing IV regression by hand:  <a href="https://andrewproctor.github.io/assets/Correcting_SE.do" style="color:teal;"> Do File </a>

<br>
</div>
<div class = "row">
<div class = "col-md-6">
<div class = "col-xs-1 col-md-0"></div>
<div class = "col-xs-11 col-md-12">
#### **Seminar Exercises**

**Panel Methods**: <a href="https://andrewproctor.github.io/assets/panel_exercise_2018_instructions.pdf" style="color:teal;">Instructions</a> | 
  <a href="https://andrewproctor.github.io/assets/panel_exercise_solutions.do" style="color:teal;">Do File</a> | 
  <a href="https://andrewproctor.github.io/assets/panel_exercise_solutions_log.txt" style="color:teal;">Log File</a> | 
  <a href="https://andrewproctor.github.io/assets/panel_exercise_regoutput.doc" style="color:teal;">Regression Output</a>

**Instrumental Variables**: <a href="https://andrewproctor.github.io/assets/IV_exercise_instructions.pdf" style="color:teal;">Instructions</a> | 
  <a href="https://andrewproctor.github.io/assets/IV_exercise_solutions.do" style="color:teal;">Do File</a> | 
  <a href="https://andrewproctor.github.io/assets/IV_exercise_solutions_log.txt" style="color:teal;">Log File</a> 
  
<br>

</div></div>
<div class = "col-md-6">
<div class = "col-xs-1 col-md-0"></div>
<div class = "col-xs-11 col-md-12">
#### **Assignments**

**Panel Methods**: <a href="https://andrewproctor.github.io/assets/panel_assignment_2018_instructions.pdf" style="color:teal;">Instructions</a> | 
  <a href="https://andrewproctor.github.io/assets/panel_assignment_2018_solutions.pdf" style="color:teal;">Solutions</a> | 
  <a href="https://andrewproctor.github.io/assets/panel_assignment_2018_solutions.do" style="color:teal;">Do File</a> | 
  <a href="https://andrewproctor.github.io/assets/panel_assignment_2018_solutions_log.txt" style="color:teal;">Log File</a>

**Instrumental Variables**: <a href="https://andrewproctor.github.io/assets/IV_assignment_2018_instructions.pdf" style="color:teal;">Instructions</a> | 
  <a href="https://andrewproctor.github.io/assets/IV_assignment_2018_solutions.pdf" style="color:teal;">Solutions</a> | 
  <a href="https://andrewproctor.github.io/assets/IV_assignment_2018_solutions.do" style="color:teal;">Do File</a> | 
  <a href="https://andrewproctor.github.io/assets/IV_assignment_2018_solutions_log.txt" style="color:teal;">Log File</a>



<br>
<br>
</div>
</div>

### **Intro to Data Science in R (SSE Masters Course 7316)**
Visit the course website at:  <a href="https://andrewproctor.github.io/rcourse/" style="color:teal;">https://andrewproctor.github.io/rcourse/</a>



